# This is a basic workflow to help you get started with Actions

name: Required workflow

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  required:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
